# Generated by Django 6.0.4 on 2026-06-27 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('ttgen', '0007_adminteacher'),
		('user_account', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='profile',
			name='linked_admin_teacher',
			field=models.ForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.SET_NULL,
				related_name='teacher_profiles',
				to='ttgen.adminteacher',
			),
		),
	]
