# Generated by Django 5.2.8 on 2026-04-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('hod', 'HOD'), ('teacher', 'Teacher'), ('dean', 'Dean')], default='', max_length=10),
        ),
    ]
