# Generated by Django 5.2.8 on 2026-04-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='institution_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
