# Generated by Codex on 2026-04-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttgen', '0001_initial'),
        ('user_account', '0002_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_account_profiles', to='ttgen.savedtimetable'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='linked_instructor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_account_profile', to='ttgen.instructor'),
        ),
    ]
