# Generated by Codex on 2026-04-26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0003_profile_teacher_dashboard_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherOnboarding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=150)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("Professor", "Professor"),
                            ("Associate Professor", "Associate Professor"),
                            ("Assistant Professor", "Assistant Professor"),
                            ("Lab Worker", "Lab Worker"),
                        ],
                        max_length=50,
                    ),
                ),
                ("joining_year", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("subjects_taught", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=models.deletion.CASCADE,
                        related_name="teacher_onboarding",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
