# Generated by Codex on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0004_teacheronboarding"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacheronboarding",
            name="requires_resubmission",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="teacheronboarding",
            name="resubmission_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
