# Generated by Django 5.2.8 on 2026-04-07 15:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Computer Science', max_length=100)),
                ('code', models.CharField(default='CS', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor')], default='Associate Professor', max_length=50)),
                ('max_workload', models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('max_numb_students', models.PositiveIntegerField()),
                ('room_required', models.CharField(choices=[('Lecture Hall', 'Lecture Hall'), ('Lab', 'Lab')], max_length=20)),
                ('required_lab_category', models.CharField(blank=True, choices=[('General', 'General'), ('Electronics Lab', 'Electronics Lab'), ('Electrical Lab', 'Electrical Lab'), ('Mechanical Workshop', 'Mechanical Workshop'), ('Electrical Workshop', 'Electrical Workshop'), ('English Lab', 'English Lab'), ('Chemistry Lab', 'Chemistry Lab'), ('Physics Lab', 'Physics Lab'), ('Animation Lab', 'Animation Lab')], default='', max_length=50)),
                ('classes_per_week', models.PositiveIntegerField(default=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='ttgen.department')),
                ('instructors', models.ManyToManyField(to='ttgen.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=5)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=15)),
                ('time', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_times', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='User', max_length=50)),
                ('avatar', models.ImageField(default='default-avatar.png', upload_to='avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ttgen_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_number', models.CharField(max_length=50)),
                ('room_type', models.CharField(choices=[('Lecture Hall', 'Lecture Hall'), ('Lab', 'Lab'), ('Seminar Room', 'Seminar Room')], max_length=20)),
                ('lab_category', models.CharField(blank=True, choices=[('General', 'General'), ('Electronics Lab', 'Electronics Lab'), ('Electrical Lab', 'Electrical Lab'), ('Mechanical Workshop', 'Mechanical Workshop'), ('Electrical Workshop', 'Electrical Workshop'), ('English Lab', 'English Lab'), ('Chemistry Lab', 'Chemistry Lab'), ('Physics Lab', 'Physics Lab'), ('Animation Lab', 'Animation Lab')], default='', max_length=50)),
                ('seating_capacity', models.PositiveIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='ttgen.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=50)),
                ('student_strength', models.PositiveIntegerField(default=70)),
                ('allowed_courses', models.ManyToManyField(blank=True, related_name='allowed_sections', to='ttgen.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ttgen.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lab', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.instructor')),
                ('lab_slots', models.ManyToManyField(blank=True, related_name='lab_extra_slots', to='ttgen.meetingtime')),
                ('meeting_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.meetingtime')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.room')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='ttgen.savedtimetable')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgen.section')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_mappings', to='ttgen.instructor')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_mappings', to='ttgen.section')),
            ],
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('user', 'code'), name='unique_dept_code_per_user'),
        ),
        migrations.AddConstraint(
            model_name='instructor',
            constraint=models.UniqueConstraint(fields=('user', 'uid'), name='unique_instructor_uid_per_user'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('user', 'course_number'), name='unique_course_number_per_user'),
        ),
        migrations.AddConstraint(
            model_name='meetingtime',
            constraint=models.UniqueConstraint(fields=('user', 'pid'), name='unique_meetingtime_pid_per_user'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('user', 'r_number'), name='unique_room_number_per_user'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('user', 'section_id'), name='unique_section_id_per_user'),
        ),
        migrations.AddConstraint(
            model_name='scheduledslot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_lab', False)), fields=('timetable', 'section', 'meeting_time'), name='unique_theory_per_section_slot'),
        ),
        migrations.AlterUniqueTogether(
            name='teachersection',
            unique_together={('instructor', 'section')},
        ),
    ]
