# Generated by Django 5.2.8 on 2026-04-11 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ttgen", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAccessPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_code",
                    models.CharField(
                        blank=True,
                        choices=[("basic", "Basic"), ("pro", "Pro")],
                        default="",
                        max_length=20,
                    ),
                ),
                ("plan_name", models.CharField(blank=True, default="", max_length=100)),
                ("amount_paid", models.PositiveIntegerField(default=0)),
                ("generations_total", models.PositiveIntegerField(default=0)),
                ("generations_used", models.PositiveIntegerField(default=0)),
                ("can_edit_delete", models.BooleanField(default=False)),
                ("can_substitute", models.BooleanField(default=False)),
                ("can_drag_drop", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("purchased_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_plan",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User access plan",
                "verbose_name_plural": "User access plans",
            },
        ),
    ]
