# Generated by Django 5.2.8 on 2026-04-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ttgen", "0002_useraccessplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedtimetable",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
