# Generated by Django 6.0.4 on 2026-04-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttgen', '0003_savedtimetable_is_published'),
        ('ttgen', '0003_teacherpreference'),
    ]

    operations = [
    ]
