# Generated by Django 6.0.4 on 2026-06-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttgen', '0003_section_mapping_extra_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('Timetable Coordinator', 'Timetable Coordinator'), ('University Timetable Coordinator', 'University Timetable Coordinator')], max_length=80)),
                ('department', models.CharField(blank=True, default='', max_length=150)),
                ('message', models.TextField(blank=True, default='')),
                ('appointed_by', models.CharField(blank=True, default='', max_length=200)),
                ('analytics_access', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['role', 'name'],
                'constraints': [models.UniqueConstraint(fields=('email', 'role'), name='unique_appointment_email_role')],
            },
        ),
    ]
