# Generated by Django 5.2.8 on 2026-04-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttgen', '0003_savedtimetable_is_published'),
        ('ttgen', '0003_teacherpreference'),
    ]

    operations = [
    ]
