# Generated by Django 6.0.4 on 2026-06-24 19:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttgen', '0004_coordinatorappointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('ip', models.CharField(blank=True, default='', max_length=60)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('login_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('action', models.CharField(choices=[('login', 'Logged in'), ('logout', 'Logged out'), ('generate', 'Generated timetable'), ('save', 'Saved timetable'), ('delete', 'Deleted'), ('export', 'Exported'), ('move', 'Moved slot (drag & drop)'), ('park', 'Parked slot'), ('restore', 'Restored slot'), ('add', 'Added slot'), ('edit', 'Edited slot'), ('substitute', 'Substituted teacher'), ('publish', 'Published'), ('unpublish', 'Unpublished'), ('other', 'Activity')], db_index=True, default='other', max_length=20)),
                ('summary', models.CharField(blank=True, default='', max_length=300)),
                ('detail', models.TextField(blank=True, default='')),
                ('path', models.CharField(blank=True, default='', max_length=300)),
                ('method', models.CharField(blank=True, default='', max_length=8)),
                ('session_key', models.CharField(blank=True, default='', max_length=60)),
                ('ip', models.CharField(blank=True, default='', max_length=60)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ttgen_activ_user_id_55b155_idx'), models.Index(fields=['action', '-created_at'], name='ttgen_activ_action_f5702a_idx')],
            },
        ),
    ]
