# Generated by Django 6.0.4 on 2026-06-24 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttgen', '0005_usersession_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructors', to='ttgen.department'),
        ),
    ]
