# Generated by Django 6.0.4 on 2026-06-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttgen', '0006_instructor_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=500)),
                ('uid', models.CharField(blank=True, default='', max_length=32)),
                ('contact_number', models.CharField(blank=True, default='', max_length=200)),
                ('designation', models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor')], default='Associate Professor', max_length=50)),
                ('department_name', models.CharField(blank=True, default='', max_length=150)),
                ('department_code', models.CharField(blank=True, default='', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'uid', 'id'],
            },
        ),
    ]
